[DefaultTextStyle]
AntiAlias=2
FontColor=#FontColor#
FontFace=#FontFace#
FontSize=12
StringEffect=SHADOW
FontEffectColor=0,0,0,200

[TODOStyle]
AntiAlias=2
FontColor=#TODOFontColor#
FontFace=Consolas
FontSize=11
StringEffect=SHADOW
FontEffectColor=0,0,0,200

[QuoteStyle]
AntiAlias=2
FontColor=#FontColor#
FontFace=#QuoteFontFace#
FontSize=12
StringEffect=SHADOW
FontEffectColor=0,0,0,255
StringEffect=SHADOW
FontEffectColor=0,0,0,200

[QuoteAuthorStyle]
AntiAlias=2
FontColor=#FontColor#
FontFace=#QuoteFontFace#
FontSize=14
StringStyle=Bold
StringEffect=SHADOW
FontEffectColor=0,0,0,200

[EventDateStyle]
AntiAlias=2
FontColor=#FontColor#
FontFace=#QuoteFontFace#
FontSize=14
StringStyle=Bold
StringEffect=SHADOW
FontEffectColor=0,0,0,200
