[Variables]
; Net settings (speedtest.net Mbps values on the left)
DownloadMax=(100 * 1048576)
UploadMax=(5 * 1048576)

; Disk settings
DriveCMax=(10 * 1048576)
DriveDMax=(10 * 1048576)
DriveFMax=(10 * 1048576)

; Events settings
CalendarURL=https://calendar.google.com/calendar/ical/wsacha67%40gmail.com/private-3339d2f00b7dc4975a229fc68b756ed0/basic.ics

; Change fonts here
FontColor=255,255,255,240
FontFace=Colibri
FontSize=13

QuoteFontFace=TrebuchetMS
TODOFontColor=255,255,255,200

; Change bars here
BarColor=255,255,255,255
BarColorDisk=D1C394
BarBackcolor=255,255,255,70
BarSize=180
BarHeight=5
TopMargin=5
